[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "thunderbird-notifications"
version = "0.0.1"
description = "Thunderbird Notifications conversion and validation tools"
requires-python = ">=3.12"
dynamic = ["dependencies"]
