name: validate-json

on:
  [push]
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.4"
      - name: Install dependencies
        run: go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest
      - name: Validate JSON files
        run: jv test/data/snapshot-schema.json test/data/json/*.json
