name: validate-json

on:
  workflow_call:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.22.4"

      - name: Install dependencies
        run: go install github.com/santhosh-tekuri/jsonschema/cmd/jv@latest

      - name: Validate JSON files
        id: validate_json
        run: |
          if [ -d "json" ] && [ "$(ls -A json/*.json 2>/dev/null)" ]; then
            jv schema.json json/*.json
          else
            echo "No JSON files to process."
          fi

      - name: Save state
        if: steps.validate_json.conclusion == 'success'
        run: echo "JV_COMMAND_SUCCESS=true" >> $GITHUB_ENV
